/**
 * EventTypes.js - Zentrale Registry für alle Event-Namen im Spiel.
 * Konsolidiert auf SCREAMING_SNAKE_CASE für maximale Konsistenz.
 */
export const EVENTS = {
    // --- CORE & STATE ---
    GAME_STATE_CHANGED: 'GAME_STATE_CHANGED',
    MISSION_STATE_CHANGED: 'MISSION_STATE_CHANGED',
    SAVE_COMPLETED: 'SAVE_COMPLETED',
    GAME_PAUSED: 'GAME_PAUSED',
    GAME_RESUMED: 'GAME_RESUMED',
    RESUME_GAME: 'RESUME_GAME',
    GAME_OVER: 'GAME_OVER',
    RELOAD_GAME: 'RELOAD_GAME',
    INTRO_COMPLETE: 'INTRO_COMPLETE',

    // --- PLAYER ---
    PLAYER_MOVED: 'PLAYER_MOVED',
    PLAYER_POSITION_UPDATED: 'PLAYER_POSITION_UPDATED',
    PLAYER_UPDATE_REQUESTED: 'PLAYER_UPDATE_REQUESTED',
    PLAYER_MOVE_INTENT: 'PLAYER_MOVE_INTENT',
    PLAYER_BUSTED: 'PLAYER_BUSTED',
    BUDGET_UPDATED: 'BUDGET_UPDATED',
    BUDGET_TICK: 'BUDGET_TICK',
    ITEMS_CHANGED: 'ITEMS_CHANGED',
    FIRST_MOVE_COMPLETED: 'FIRST_MOVE_COMPLETED',
    TOGGLE_BICYCLE: 'TOGGLE_BICYCLE',
    
    // --- MAP & POIs ---
    TARGETS_UPDATED: 'TARGETS_UPDATED',
    CAMERA_FIT_BOUNDS_REQUESTED: 'CAMERA_FIT_BOUNDS_REQUESTED',
    PUB_TARGET_REACHED: 'PUB_TARGET_REACHED',
    SPAWN_TARGETS: 'SPAWN_TARGETS',
    DATA_LOADED: 'DATA_LOADED',
    API_FETCH_START: 'API_FETCH_START',
    START_MAP_INTRO: 'START_MAP_INTRO',
    MAP_LOAD_START: 'MAP_LOAD_START',
    MAP_LOAD_PROGRESS: 'MAP_LOAD_PROGRESS',
    MAP_LOAD_SUCCESS: 'MAP_LOAD_SUCCESS',
    MAP_LOAD_ERROR: 'MAP_LOAD_ERROR',

    // --- UI & DIALOGS ---
    SHOW_TOAST: 'SHOW_TOAST',
    SHOW_DIALOG: 'SHOW_DIALOG',
    SHOW_INFO_CASCADE: 'SHOW_INFO_CASCADE',
    SHOW_ENCOUNTER: 'SHOW_ENCOUNTER',
    SHOW_LOAN_MODAL: 'SHOW_LOAN_MODAL',
    CLOSE_INTERACTION: 'CLOSE_INTERACTION',
    OPEN_INTERACTION: 'OPEN_INTERACTION',
    OPEN_SCOUTING_REPORT: 'OPEN_SCOUTING_REPORT',
    OPEN_INVESTMENT: 'OPEN_INVESTMENT',
    INFO_UPDATED: 'INFO_UPDATED',
    INFO_MENU_STATE: 'INFO_MENU_STATE',
    TOGGLE_INFO: 'TOGGLE_INFO',
    SHOW_TUTORIAL: 'SHOW_TUTORIAL',
    FLYING_REWARD: 'FLYING_REWARD',
    FLYING_INFO: 'FLYING_INFO',
    
    // --- LOGBOOK ---
    ADD_LOG_ENTRY: 'ADD_LOG_ENTRY',
    REMOVE_LOG_ENTRY: 'REMOVE_LOG_ENTRY',
    COMPLETE_LOG_ENTRY: 'COMPLETE_LOG_ENTRY',

    // --- GAMEPLAY FLOWS ---
    INTERACTION_SELECTED: 'INTERACTION_SELECTED',
    START_BURGLARY: 'START_BURGLARY',
    START_BICYCLE_THEFT_RNG: 'START_BICYCLE_THEFT_RNG',
    ENCOUNTER_TRIGGERED: 'ENCOUNTER_TRIGGERED',
    RADAR_ACKNOWLEDGED: 'RADAR_ACKNOWLEDGED',
    RADAR_SEQUENCE_START: 'RADAR_SEQUENCE_START',
    
    // --- PURCHASES & SHOPS ---
    BUY_BOLT_CUTTER: 'BUY_BOLT_CUTTER',
    INVESTMENT_CANCELLED: 'INVESTMENT_CANCELLED',
    ACCEPT_LOAN_OFFER: 'ACCEPT_LOAN_OFFER',
    REJECT_LOAN: 'REJECT_LOAN',
    BARBER_CONTACT_BUY_TICKET: 'BARBER_CONTACT_BUY_TICKET',
    BARBER_CONTACT_CANCEL: 'BARBER_CONTACT_CANCEL',
    BUY_BARBER_TICKET: 'BUY_BARBER_TICKET',
    
    // --- REVEALS & SEQUENCES ---
    START_POLICE_REVEAL: 'START_POLICE_REVEAL',
    START_BARBER_REVEAL: 'START_BARBER_REVEAL',
    BARBER_TRANSFORM_START: 'BARBER_TRANSFORM_START',

    // --- LEGACY / CUSTOM OPTIONS ---
    OPTION_C_CLICKED: 'OPTION_C_CLICKED',
    OPTION_D_CLICKED: 'OPTION_D_CLICKED',
    
    // --- GAMEPLAY RESULTS ---
    BICYCLE_THEFT_SUCCESS: 'BICYCLE_THEFT_SUCCESS',
    BICYCLE_THEFT_FAILURE: 'BICYCLE_THEFT_FAILURE',
    BICYCLE_THEFT_SUCCESS_DONE: 'BICYCLE_THEFT_SUCCESS_DONE',
    BURGLARY_SUCCESS: 'BURGLARY_SUCCESS',
    BURGLARY_FAILURE: 'BURGLARY_FAILURE',

    // --- CATEGORY SELECTION ---
    SELECT_CATEGORY_RESIDENTIAL: 'SELECT_CATEGORY_RESIDENTIAL',
    SELECT_CATEGORY_COMMERCIAL: 'SELECT_CATEGORY_COMMERCIAL',
    SELECT_CATEGORY_PUBLIC: 'SELECT_CATEGORY_PUBLIC',
    SELECT_CATEGORY_ALLOTMENTS: 'SELECT_CATEGORY_ALLOTMENTS'
};
