/**
 * EventTypes.js - Zentrale Registry für alle Event-Namen im Spiel.
 * Konsolidiert auf SCREAMING_SNAKE_CASE für maximale Konsistenz.
 */
export const EVENTS = {
    // --- CORE & STATE ---
    GAME_STATE_CHANGED: 'GAME_STATE_CHANGED',
    MISSION_STATE_CHANGED: 'MISSION_STATE_CHANGED',
    SAVE_COMPLETED: 'SAVE_COMPLETED',

    // --- PLAYER ---
    PLAYER_MOVED: 'PLAYER_MOVED',
    PLAYER_POSITION_UPDATED: 'PLAYER_POSITION_UPDATED',
    PLAYER_BUSTED: 'PLAYER_BUSTED',
    BUDGET_UPDATED: 'BUDGET_UPDATED',
    BUDGET_TICK: 'BUDGET_TICK',
    ITEMS_CHANGED: 'ITEMS_CHANGED',

    // --- MAP & POIs ---
    TARGETS_UPDATED: 'TARGETS_UPDATED',
    CAMERA_FIT_BOUNDS_REQUESTED: 'CAMERA_FIT_BOUNDS_REQUESTED',
    PUB_TARGET_REACHED: 'PUB_TARGET_REACHED',

    // --- UI & DIALOGS ---
    SHOW_TOAST: 'SHOW_TOAST',
    SHOW_DIALOG: 'SHOW_DIALOG',
    SHOW_INFO_CASCADE: 'SHOW_INFO_CASCADE',
    CLOSE_INTERACTION: 'CLOSE_INTERACTION',
    OPEN_INTERACTION: 'OPEN_INTERACTION',
    OPEN_SCOUTING_REPORT: 'OPEN_SCOUTING_REPORT',
    INFO_UPDATED: 'INFO_UPDATED',
    INFO_MENU_STATE: 'INFO_MENU_STATE',
    
    // --- ACTIONS ---
    START_MAP_INTRO: 'START_MAP_INTRO',
    START_POLICE_REVEAL: 'START_POLICE_REVEAL',
    RADAR_SEQUENCE_START: 'RADAR_SEQUENCE_START',
    BARBER_TRANSFORM_START: 'BARBER_TRANSFORM_START',
    START_BICYCLE_THEFT_RNG: 'START_BICYCLE_THEFT_RNG'
};
